repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: detect-private-key
    -   id: name-tests-test
        args: [--pytest-test-first]
    - id: no-commit-to-branch
      args: [--branch, main]

-   repo: local
    hooks:
      - id: ruff-check-local
        name: ruff-check(local-env)
        entry: ruff check
        language: system
        types: [python]
        args: [--config=./pyproject.toml, --force-exclude]
        require_serial: true

-   repo: local
    hooks:
      - id: ruff-format-local
        name: ruff-format(local-env)
        entry: ruff format
        language: system
        types: [python]
        args: [--config=./pyproject.toml, --force-exclude]
        require_serial: true

-   repo: local
    hooks:
      - id: mypy-local
        name: mypy(local-env)
        entry: mypy
        language: system
        types: [python]
        args: [--config-file=./pyproject.toml]
        require_serial: true

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.10
    hooks:
      - id: uv-lock
