[project]
name = "m8_team"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "streamlit==1.34.0",
    "firebase-admin==6.4.0",
    "streamlit-authenticator==0.3.1",
    "streamlit-echarts==0.4.0",
    "streamlit-option-menu==0.3.6",
    "python-dotenv==1.0.1",
    "requests==2.32.5",
]

[build-system]
requires = ["uv-build>=0.8,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.12"
strict = true
mypy_path = "src"

[[tool.mypy.overrides]]
module = [
    "firebase_admin",
    "firebase_admin.*",
    "pandas.*",
    "streamlit_echarts.*",
    "streamlit_option_menu.*",
    "streamlit_authenticator.*"
]
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src/m8_team"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[dependency-groups]
dev = [
    "mypy>=1.20.0",
    "ruff>=0.15.10",

    "pytest>=9.0.0",
    "pytest-mock>=3.14.0",
    "pytest-cov>=5.0.0",
    "types-requests==2.32.4.20250913",
    "pre-commit==4.6.0"
]